### ISSUE TITLE
Devtool is not tracking actions

### ISSUE THREAD

**Issue by pitops** [bluebill1049/little-state-machine-dev-tools#13]
Devtool is not working even in [link](https://codesandbox.io/s/lrz5wloklm) provided by the package. Clicking actions in form update the localStorage and shown in devtool but not the actions

Also tried locally with same result. 

Resetting also doesn't work. The window variable is different

**Comment by bluebill1049** [comment]
Thanks, looks like there is a bug in the dev tool.
