### ISSUE TITLE
Point to latest version in peer dependencies of little-state-machine in package.json

### ISSUE THREAD

**Issue by onlyphantom** [bluebill1049/little-state-machine-dev-tools#19]
When installing this package, it looks like its `peerDependencies` look for `ittle-state-machine` version 3.0.0. [Copied from the `package.json`](https://github.com/bluebill1049/little-state-machine-dev-tools/blob/master/package.json) at its current release (version 2.0.0):

```
  "peerDependencies": {
    "little-state-machine": "^3.0.0",
    "react": "^16.8.0",
    "react-dom": "^16.8.0"
  },
  "dependencies": {
    "little-state-machine": "^4.0.2",
    "lodash.clonedeep": "^4.5.0",
    "lodash.isempty": "^4.4.0",
    "lodash.isequal": "^4.5.0",
    "lodash.isobject": "^3.0.2",
    "lodash.transform": "^4.6.0",
    "react-json-view": "^1.19.1",
    "react-simple-animate": "^3.3.0"
  }
```

So if a user only have little-state-machine 4.0.2, trying to do an install (`npm install little-state-machine-devtools --save-dev`) will throw an error, asking the user to either fix the upstream dependency conflict, or use `--force` to accept the broken dependency resolution:

> npm ERR! Could not resolve dependency:
> npm ERR! peer little-state-machine@"^3.0.0" from little-state-machine-devtools@2.0.0

Should we bump both to the latest version? Should we just go ahead with `--legacy-peer-deps`? What do you recommend?

Thanks for the awesome package!

**Comment by bluebill1049** [comment]
let's point to the latest. Do you want to send a PR?

**Comment by onlyphantom** [comment]
Thank you for the fast response; Submitted #20  to bump the version. Feel free to close the issue! This should also [fix the demo that is linked to](https://codesandbox.io/s/lrz5wloklm) on the github readme:

<img width="1430" alt="Screen Shot 2021-03-04 at 13 59 45" src="https://user-images.githubusercontent.com/16984453/109923881-043d7b00-7cf2-11eb-9cae-e2c40867187f.png">

**Comment by bluebill1049** [comment]
thanks, patch released.
