### ISSUE TITLE
Actions not logged, Reset button not working

### ISSUE THREAD

**Issue by ptim** [bluebill1049/little-state-machine-dev-tools#5]
Hi! Enjoying LSM so far - many thanks!

Just an FYI - I can see the state change, but I'm not seeing any actions logged, and the reset button has no effect. I don't think the Save,Load state buttons are working either, but I haven't tested them very thoroughly.

I don't see any related errors in the console.

`"little-state-machine-devtools": "^1.0.0",`

MacOS Chrome 83, incognito tab, only two extensions active: react devtools and fullpage screencapture

Thanks for your efforts - will chime in if I can see any place to help 🙏

**Comment by bluebill1049** [comment]
can you provide a codesandbox?

**Comment by bluebill1049** [comment]
oh i see, those functions are internal functions, they don't have specific actions.

**Comment by ptim** [comment]
Aha! Thanks - is there a way to configure those functions without forking the devtool? Do you know of any examples in the wild where they're already configured?

It doesn't seem that they're configured in this repo's examples.. I'd be happy to write up some docs if you can point me in the right direction!
 
https://codesandbox.io/s/github/bluebill1049/little-state-machine-dev-tools/tree/master/example

**Comment by bluebill1049** [comment]
I think wan include that as a feature tho, you want to take a look and send a PR?

**Comment by ptim** [comment]
Sweet! Will look into it, thanks 👍
