### ISSUE TITLE
Not working with react 17

### ISSUE THREAD

**Issue by HadiSDev** [bluebill1049/little-state-machine-dev-tools#50]
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from little-state-machine-devtools@2.0.1
npm ERR! node_modules/little-state-machine-devtools
npm ERR!   little-state-machine-devtools@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by minorgod** [comment]
Here's a PR for this: 
https://github.com/bluebill1049/little-state-machine-dev-tools/pull/55
